"""Build the technical math presentation as an editable .pptx.

Uses real project assets (sim frames, plots, diagrams) generated by
gen_math_assets.py and captured from parafoil_sim/output.

    python presentation/gen_math_assets.py   # once, or after code changes
    python presentation/build_math_deck.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Emu, Inches, Pt

ROOT = Path(__file__).resolve().parents[1]
ASSETS = Path(__file__).resolve().parent / "assets"
FRAMES = ASSETS / "frames"

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)
MARGIN = Inches(0.55)
BODY_W = SLIDE_W - 2 * MARGIN

THEME = {
    "bg": RGBColor(0x0B, 0x1D, 0x33),
    "bg_alt": RGBColor(0x10, 0x27, 0x42),
    "panel": RGBColor(0x16, 0x31, 0x50),
    "accent": RGBColor(0x35, 0xC8, 0xD6),
    "accent2": RGBColor(0xF2, 0xA9, 0x3B),
    "text": RGBColor(0xF2, 0xF6, 0xFA),
    "muted": RGBColor(0x9B, 0xB0, 0xC4),
    "rule": RGBColor(0x27, 0x45, 0x67),
}
FONT_HEAD = "Calibri"
FONT_BODY = "Calibri"
FONT_EQ = "Consolas"


def new_deck() -> Presentation:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    return prs


def blank(prs, bg=None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = bg or THEME["bg"]
    return slide


def rect(slide, left, top, width, height, color, *, shape=MSO_SHAPE.RECTANGLE):
    sh = slide.shapes.add_shape(shape, left, top, width, height)
    sh.fill.solid()
    sh.fill.fore_color.rgb = color
    sh.line.fill.background()
    sh.shadow.inherit = False
    return sh


def textbox(slide, left, top, width, height):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = Pt(0)
    return tf


def write(
    tf,
    text,
    *,
    size=16,
    color=None,
    bold=False,
    italic=False,
    font=FONT_BODY,
    align=PP_ALIGN.LEFT,
    space_before=0,
    space_after=0,
    line_spacing=1.2,
    first=False,
):
    para = tf.paragraphs[0] if first else tf.add_paragraph()
    para.alignment = align
    para.space_before = Pt(space_before)
    para.space_after = Pt(space_after)
    para.line_spacing = line_spacing
    run = para.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.name = font
    run.font.color.rgb = color or THEME["text"]
    return para


def kicker(slide, label):
    rect(slide, MARGIN, Inches(0.38), Inches(0.14), Inches(0.14), THEME["accent"])
    tf = textbox(slide, MARGIN + Inches(0.28), Inches(0.32), Inches(10), Inches(0.35))
    write(tf, label.upper(), size=11, color=THEME["accent"], bold=True, first=True)


def heading(slide, title, *, top=Inches(0.7), size=28, width=None):
    tf = textbox(slide, MARGIN, top, width or BODY_W, Inches(0.7))
    write(tf, title, size=size, color=THEME["text"], bold=True, font=FONT_HEAD,
          line_spacing=1.05, first=True)


def footer(slide, index, total):
    tf = textbox(slide, MARGIN, SLIDE_H - Inches(0.42), BODY_W - Inches(1.2), Inches(0.28))
    write(tf, "Luna · Parafoil NMPC math  ·  source: papers/parafoil_mpc_math",
          size=9, color=THEME["muted"], first=True)
    tf2 = textbox(slide, SLIDE_W - MARGIN - Inches(1.1), SLIDE_H - Inches(0.42),
                  Inches(1.1), Inches(0.28))
    write(tf2, f"{index}/{total}", size=9, color=THEME["muted"],
          align=PP_ALIGN.RIGHT, first=True)


def add_image(slide, path: Path, left, top, width=None, height=None):
    if not path.exists():
        raise FileNotFoundError(path)
    return slide.shapes.add_picture(str(path), left, top, width=width, height=height)


def eq_panel(slide, left, top, width, height, lines, *, title=None):
    """Editable monospace equation block."""
    rect(slide, left, top, width, height, THEME["panel"])
    rect(slide, left, top, Inches(0.05), height, THEME["accent"])
    y = top + Inches(0.12)
    if title:
        tf = textbox(slide, left + Inches(0.2), y, width - Inches(0.35), Inches(0.28))
        write(tf, title, size=11, color=THEME["accent"], bold=True, first=True)
        y += Inches(0.3)
    tf = textbox(slide, left + Inches(0.2), y, width - Inches(0.35),
                 height - (y - top) - Inches(0.1))
    for i, line in enumerate(lines):
        write(tf, line, size=13, color=THEME["text"], font=FONT_EQ,
              space_before=4 if i else 0, line_spacing=1.25, first=(i == 0))


def explain(slide, left, top, width, items):
    """Numbered short explanations."""
    y = top
    for i, (head, body) in enumerate(items, 1):
        tf = textbox(slide, left, y, width, Inches(0.85))
        write(tf, f"{i}. {head}", size=14, color=THEME["accent"], bold=True, first=True)
        write(tf, body, size=12, color=THEME["muted"], space_before=2, line_spacing=1.2)
        y += Inches(0.85)
    return y


def load_json(name):
    return json.loads((ASSETS / name).read_text())


# --------------------------------------------------------------------------- #
# slides
# --------------------------------------------------------------------------- #
TOTAL = 16


def s01_title(prs):
    slide = blank(prs)
    rect(slide, Emu(0), Emu(0), Inches(0.2), SLIDE_H, THEME["accent"])
    tf = textbox(slide, MARGIN, Inches(1.6), Inches(7.2), Inches(0.4))
    write(tf, "GUIDED PARACHUTE PROJECT  ·  MATH WALKTHROUGH", size=12,
          color=THEME["accent"], bold=True, first=True)
    tf = textbox(slide, MARGIN, Inches(2.15), Inches(7.5), Inches(1.6))
    write(tf, "Nonlinear MPC for\nParafoil Return-to-Pad", size=40,
          color=THEME["text"], bold=True, font=FONT_HEAD, line_spacing=1.05, first=True)
    rect(slide, MARGIN, Inches(4.0), Inches(1.6), Inches(0.04), THEME["accent2"])
    tf = textbox(slide, MARGIN, Inches(4.25), Inches(7.2), Inches(1.2))
    write(tf,
          "Equations from papers/parafoil_mpc_math.pdf — kinematic plant, "
          "power-law + OU wind, GPS wind estimate, shrinking-horizon NMPC — "
          "plus results and frames from the project simulator.",
          size=15, color=THEME["muted"], line_spacing=1.35, first=True)
    tf = textbox(slide, MARGIN, Inches(6.3), Inches(7), Inches(0.35))
    write(tf, "Hudson Kim  ·  editable PowerPoint  ·  project assets only",
          size=12, color=THEME["muted"], first=True)

    # Real sim frame on the right
    img = FRAMES / "t40_mid.png"
    if img.exists():
        add_image(slide, img, Inches(8.15), Inches(1.55), width=Inches(4.7))
    footer(slide, 1, TOTAL)


def s02_architecture(prs):
    slide = blank(prs)
    kicker(slide, "System")
    heading(slide, "How the pieces connect")
    add_image(slide, ASSETS / "diagram_closed_loop.png",
              MARGIN, Inches(1.55), width=Inches(12.2))
    tf = textbox(slide, MARGIN, Inches(5.55), BODY_W, Inches(1.3))
    write(tf, "Key idea", size=14, color=THEME["accent"], bold=True, first=True)
    write(tf,
          "The plant always feels truth wind (shear + gusts). The controller never "
          "sees that wind — only a filtered estimate ŵ held constant inside each "
          "NMPC prediction. Receding-horizon replanning every Tc = 1 s is what "
          "absorbs the mismatch.",
          size=14, color=THEME["muted"], space_before=4, line_spacing=1.3)
    footer(slide, 2, TOTAL)


def s03_state_control(prs):
    slide = blank(prs)
    kicker(slide, "Vehicle model")
    heading(slide, "State, control, coordinated turn")
    eq_panel(slide, MARGIN, Inches(1.55), Inches(6.4), Inches(2.55), [
        "x = [ p_x,  p_y,  h,  ψ ]ᵀ",
        "",
        "u = ψ̇          |u| ≤ u_max = 0.35 rad/s",
        "",
        "u = (g / V_h) tan φ     (coordinated turn)",
    ], title="Definitions")
    explain(slide, Inches(7.2), Inches(1.55), Inches(5.5), [
        ("State x", "Planar position, altitude above the pad plane, air-relative heading."),
        ("Control u", "Commanded heading rate. Physical actuator = asymmetric brake deflection."),
        ("Bank limit", "The bound on u is a bank-angle limit via the coordinated-turn map."),
    ])
    tf = textbox(slide, MARGIN, Inches(4.4), BODY_W, Inches(2.2))
    write(tf, "Defaults used in the paper / algo/mpc_v1", size=13,
          color=THEME["accent"], bold=True, first=True)
    write(tf, "V_h = 7.0 m/s    V_v = 3.5 m/s    glide ratio = 2",
          size=14, color=THEME["text"], font=FONT_EQ, space_before=8)
    write(tf, "x₀ = [650, −450, 500, π/2]ᵀ m,rad     r_t = [0, 0]ᵀ (pad)",
          size=14, color=THEME["text"], font=FONT_EQ, space_before=6)
    write(tf,
          "Why this order? Fixed glide numbers make time-to-go a pure function of "
          "altitude: t_go = h / V_v. That fact drives the shrinking horizon later.",
          size=13, color=THEME["muted"], space_before=12, line_spacing=1.25)
    footer(slide, 3, TOTAL)


def s04_kinematics(prs):
    slide = blank(prs)
    kicker(slide, "Vehicle model")
    heading(slide, "Kinematic dynamics — where wind enters")
    eq_panel(slide, MARGIN, Inches(1.5), Inches(6.0), Inches(3.2), [
        "ẋ = V_h cos ψ  +  w_x",
        "ẏ = V_h sin ψ  +  w_y",
        "ḣ = −V_v",
        "ψ̇ = u",
        "",
        "t_go = h / V_v",
    ], title="3-DOF plant  (eq. dynamics)")
    add_image(slide, ASSETS / "diagram_kinematics.png",
              Inches(6.7), Inches(1.45), width=Inches(6.1))
    tf = textbox(slide, MARGIN, Inches(5.0), BODY_W, Inches(1.7))
    write(tf, "Reading the equations", size=13, color=THEME["accent"], bold=True, first=True)
    write(tf,
          "• Horizontal ground velocity is air velocity plus wind — wind can rival V_h near the surface.\n"
          "• Altitude falls at a fixed sink rate, so remaining flight time is a clock.\n"
          "• The only decision the guidance law makes is the heading-rate sequence u(t).",
          size=13, color=THEME["muted"], space_before=4, line_spacing=1.35)
    footer(slide, 4, TOTAL)


def s05_wind(prs):
    slide = blank(prs)
    kicker(slide, "Atmosphere")
    heading(slide, "Truth wind: shear + gusts (controller never sees this)")
    eq_panel(slide, MARGIN, Inches(1.45), Inches(5.8), Inches(3.4), [
        "w(h,t) = w_mean(h) + ξ(t)",
        "",
        "|w_mean| = W₁₀ (max(h,h_min)/10)^α",
        "w_mean = |w_mean| [cos θ_w, sin θ_w]ᵀ",
        "",
        "ξ_{k+1} = (1 − Δt/τ_g) ξ_k",
        "         + σ_g √(2Δt/τ_g) η_k",
        "η_k ~ N(0, I₂)",
    ], title="Power law + Ornstein–Uhlenbeck")
    add_image(slide, ASSETS / "diagram_wind.png",
              Inches(6.5), Inches(1.4), width=Inches(6.3))
    tf = textbox(slide, MARGIN, Inches(5.15), BODY_W, Inches(1.6))
    write(tf,
          "Defaults: W₁₀ = 3 m/s, θ_w = 210°, α = 0.14, h_min = 2 m, "
          "τ_g = 8 s, σ_g = 0.8 m/s. OU is a lightweight stand-in for Dryden "
          "turbulence — enough to stress guidance without full spectral fidelity.",
          size=13, color=THEME["muted"], line_spacing=1.3, first=True)
    footer(slide, 5, TOTAL)


def s06_estimator(prs):
    slide = blank(prs)
    kicker(slide, "Sensing")
    heading(slide, "GPS sensing → low-pass wind estimate")
    eq_panel(slide, MARGIN, Inches(1.5), Inches(7.0), Inches(3.5), [
        "v_air = V_h [cos ψ, sin ψ]ᵀ",
        "v_GPS = v_air + w + ν,   ν ~ N(0, σ_GPS² I)",
        "w_raw = v_GPS − v_air",
        "",
        "ŵ ← ŵ + a (w_raw − ŵ)",
        "a = Δt / (Δt + τ_e)",
        "",
        "NMPC holds ŵ constant over the horizon",
    ], title="Estimator (runs every plant step Δt)")
    explain(slide, Inches(7.8), Inches(1.55), Inches(4.9), [
        ("Assumes known airspeed & heading", "Navigation errors beyond ground-velocity noise are out of scope in the paper."),
        ("σ_GPS = 0.2 m/s, τ_e = 5 s", "Filter trades noise rejection against lag on shear changes."),
        ("Frozen ŵ in prediction", "Structural mismatch vs altitude-varying truth — fixed by replanning."),
    ])
    footer(slide, 6, TOTAL)


def s07_horizon(prs):
    slide = blank(prs)
    kicker(slide, "NMPC")
    heading(slide, "Decision variables and shrinking horizon")
    add_image(slide, ASSETS / "diagram_horizon.png",
              MARGIN, Inches(1.4), width=Inches(12.2))
    eq_panel(slide, MARGIN, Inches(5.0), Inches(12.2), Inches(1.7), [
        "U = [u₀, u₁, …, u_{N−1}]ᵀ ,   |u_i| ≤ u_max",
        "N = min( N_max, max(3, ⌈ t_go / T_s ⌉) )     N_max=25, T_s=2 s, T_c=1 s",
        "Warm start: shift previous U one step; pad/trim to length N. Predict with RK4 under frozen ŵ.",
    ], title="Program")
    footer(slide, 7, TOTAL)


def s08_cost(prs):
    slide = blank(prs)
    kicker(slide, "NMPC")
    heading(slide, "Cost function — what “good” means")
    add_image(slide, ASSETS / "diagram_cost.png",
              MARGIN, Inches(1.35), width=Inches(12.2))
    eq_panel(slide, MARGIN, Inches(4.85), Inches(12.2), Inches(1.9), [
        "J(U) = Σ [ Q_path‖r_i−r_t‖² + R_u u_i² + R_Δu (u_i−u_{i−1})² + 1_{h<h_ap} Q_head e_i² ]",
        "     + Q_f (1 + c_term / max(h_{N'}, 5)) ‖r_{N'}−r_t‖²",
        "e_i = wrapped heading error to upwind of ŵ     h_ap=60 m",
        "Weights: Q_path=0.02, R_u=2, R_Δu=4, Q_f=1, c_term=200, Q_head=40",
    ], title="Scalar cost (solve with SQP / fmincon; apply only u₀)")
    footer(slide, 8, TOTAL)


def s09_video_storyboard(prs):
    slide = blank(prs)
    kicker(slide, "Simulation video")
    heading(slide, "Frames from steady_wind_flight.mp4")
    frames = [
        (FRAMES / "t00_release.png", "t ≈ 0 s · release"),
        (FRAMES / "t15_homing.png", "t ≈ 15 s · homing"),
        (FRAMES / "t40_mid.png", "t ≈ 40 s · mid / loiter"),
        (FRAMES / "t_end_touchdown.png", "touchdown"),
    ]
    # 2×2 grid sized so captions + footer clear the bottom
    w = Inches(5.85)
    h_img = Inches(2.45)
    gap_x, gap_y = Inches(0.4), Inches(0.42)
    for i, (path, caption) in enumerate(frames):
        col, row = i % 2, i // 2
        left = MARGIN + col * (w + gap_x)
        top = Inches(1.15) + row * (h_img + gap_y)
        if path.exists():
            add_image(slide, path, left, top, height=h_img)
        tf = textbox(slide, left, top + h_img + Inches(0.02), w, Inches(0.28))
        write(tf, caption, size=12, color=THEME["accent"], bold=True, first=True)
    footer(slide, 9, TOTAL)


def s10_video_sequence(prs):
    slide = blank(prs)
    kicker(slide, "Simulation video")
    heading(slide, "Evenly spaced sequence (every ~8 s)")
    seq = sorted(FRAMES.glob("vid_seq_*.png"))[:8]
    # one row of 4 then another row of 4
    for i, path in enumerate(seq):
        col, row = i % 4, i // 4
        left = MARGIN + Inches(col * 3.15)
        top = Inches(1.4) + Inches(row * 2.75)
        add_image(slide, path, left, top, width=Inches(3.0))
        tf = textbox(slide, left, top + Inches(1.72), Inches(3.0), Inches(0.25))
        write(tf, f"frame {i+1}/8", size=10, color=THEME["muted"], first=True)
    tf = textbox(slide, MARGIN, Inches(6.85), BODY_W, Inches(0.3))
    write(tf, "Full video: presentation/assets/steady_wind_flight.mp4  "
              "(also parafoil_sim/output/steady_wind_flight.mp4)",
          size=11, color=THEME["muted"], first=True)
    footer(slide, 10, TOTAL)


def s11_mpc_results(prs):
    slide = blank(prs)
    kicker(slide, "Results · kinematic NMPC (algo/mpc_v1)")
    heading(slide, "Ground track under sheared / gusty truth wind")
    add_image(slide, ASSETS / "mpc_ground_track.png",
              MARGIN, Inches(1.35), width=Inches(7.0))
    summ = load_json("mpc_summary.json")
    # Paper reports ~22.2 m with MATLAB rng; Python port got ~13 m — disclose both
    rect(slide, Inches(7.7), Inches(1.5), Inches(5.0), Inches(4.8), THEME["panel"])
    tf = textbox(slide, Inches(7.95), Inches(1.7), Inches(4.55), Inches(4.4))
    write(tf, "What this plot shows", size=14, color=THEME["accent"], bold=True, first=True)
    write(tf,
          f"• Flight time ≈ {summ['t_flight_s']:.1f} s\n"
          f"• Python-port miss ≈ {summ['miss_m']:.1f} m (seed 2)\n"
          "• Paper (MATLAB rng) miss ≈ 22.2 m (seed 2)\n"
          "• Same equations; RNG streams differ\n\n"
          "Grey arrows = truth wind samples along the path.\n"
          "Red star = pad. White circle = release.\n\n"
          "Qualitative pattern (paper):\n"
          "clear large offset early; terminal weight + upwind heading dominate the last tens of meters.",
          size=13, color=THEME["text"], space_before=8, line_spacing=1.3)
    footer(slide, 11, TOTAL)


def s12_mpc_control(prs):
    slide = blank(prs)
    kicker(slide, "Results · kinematic NMPC")
    heading(slide, "Control effort and wind estimate vs truth")
    add_image(slide, ASSETS / "mpc_control_wind.png",
              MARGIN, Inches(1.35), width=Inches(8.0))
    explain(slide, Inches(8.3), Inches(1.55), Inches(4.5), [
        ("Heading rate u(t)", "Stays inside ±u_max. Red dashed = bank limits."),
        ("W_x / W_y", "Blue = truth (shear + OU). Orange dashed = ŵ from GPS LPF."),
        ("Lag is visible", "Estimator trails gusts; NMPC still closes because it replans."),
    ])
    footer(slide, 12, TOTAL)


def s13_mpc_closing(prs):
    slide = blank(prs)
    kicker(slide, "Results · kinematic NMPC")
    heading(slide, "Closing the pad & 3-D descent")
    add_image(slide, ASSETS / "mpc_range_vs_alt.png",
              MARGIN, Inches(1.4), width=Inches(6.1))
    add_image(slide, ASSETS / "mpc_trajectory_3d.png",
              Inches(6.9), Inches(1.4), width=Inches(5.9))
    tf = textbox(slide, MARGIN, Inches(6.35), BODY_W, Inches(0.55))
    write(tf,
          "Left: distance-to-pad vs altitude (altitude axis reversed — reading left→right "
          "is descending). Right: same trajectory in 3-D.",
          size=13, color=THEME["muted"], first=True)
    footer(slide, 13, TOTAL)


def s14_sim_results(prs):
    slide = blank(prs)
    kicker(slide, "Results · 6-DOF project simulator")
    heading(slide, "parafoil_sim steady_wind — phased ground track")
    add_image(slide, ASSETS / "sim_steady_wind_track.png",
              MARGIN, Inches(1.35), width=Inches(7.0))
    add_image(slide, ASSETS / "preview_follow.png",
              Inches(7.7), Inches(1.4), width=Inches(5.0))
    summ = load_json("sim_steady_wind_summary.json")
    tf = textbox(slide, Inches(7.7), Inches(4.7), Inches(5.0), Inches(1.9))
    write(tf, "steady_wind summary", size=13, color=THEME["accent"], bold=True, first=True)
    write(tf,
          f"miss = {summ['miss_distance_m']:.1f} m\n"
          f"flight = {summ['t_flight_s']:.0f} s\n"
          f"touchdown ground speed = {summ['td_ground_speed_mps']:.1f} m/s\n"
          f"flare triggered = {summ['flare_triggered']}",
          size=13, color=THEME["text"], font=FONT_EQ, space_before=6, line_spacing=1.35)
    footer(slide, 14, TOTAL)


def s15_sim_scenarios(prs):
    slide = blank(prs)
    kicker(slide, "Results · 6-DOF project simulator")
    heading(slide, "Scenario sweep — miss distances")
    # 2x2 tracks
    names = [
        ("calm", "Calm"),
        ("steady_wind", "Steady wind"),
        ("shear_turbulence", "Shear + turbulence"),
        ("strong_gusts", "Strong gusts"),
    ]
    for i, (key, label) in enumerate(names):
        col, row = i % 2, i // 2
        left = MARGIN + Inches(col * 6.35)
        top = Inches(1.3) + Inches(row * 2.85)
        img = ASSETS / f"sim_{key}_track.png"
        if img.exists():
            add_image(slide, img, left, top, width=Inches(6.1))
        summ = load_json(f"sim_{key}_summary.json")
        tf = textbox(slide, left, top + Inches(2.35), Inches(6.1), Inches(0.28))
        write(tf, f"{label}: miss {summ['miss_distance_m']:.1f} m",
              size=11, color=THEME["accent"], bold=True, first=True)
    footer(slide, 15, TOTAL)


def s16_takeaways(prs):
    slide = blank(prs)
    kicker(slide, "Takeaways")
    heading(slide, "What the math is saying")
    cards = [
        (MARGIN, "Transparent plant",
         "3-DOF kinematics + fixed glide. Wind is the hard part, not aeroelasticity."),
        (Inches(4.7), "Estimate ≠ truth",
         "ŵ is a lagged, noisy reconstruction held frozen in prediction."),
        (Inches(8.85), "Replan absorbs mismatch",
         "Structural shear/gust error is acceptable if you replan every Tc."),
    ]
    for left, title, body in cards:
        rect(slide, left, Inches(1.55), Inches(3.9), Inches(2.4), THEME["panel"])
        rect(slide, left, Inches(1.55), Inches(0.06), Inches(2.4), THEME["accent"])
        tf = textbox(slide, left + Inches(0.3), Inches(1.75), Inches(3.4), Inches(2.0))
        write(tf, title, size=16, color=THEME["accent"], bold=True, first=True)
        write(tf, body, size=13, color=THEME["muted"], space_before=10, line_spacing=1.3)

    # Hardware sketch + video path
    sketch = ASSETS / "rough_sketch.png"
    if sketch.exists():
        add_image(slide, sketch, MARGIN, Inches(4.2), height=Inches(2.5))
    tf = textbox(slide, Inches(4.7), Inches(4.3), Inches(8.0), Inches(2.3))
    write(tf, "Sources in this deck", size=14, color=THEME["accent"], bold=True, first=True)
    write(tf,
          "• Math: papers/parafoil_mpc_math.pdf  +  algo/mpc_v1/*.m\n"
          "• Plots: regenerated by presentation/gen_math_assets.py\n"
          "• Video / frames: parafoil_sim/output/steady_wind_flight.mp4\n"
          "• 6-DOF results: parafoil_sim/output/*_flight.json\n"
          "• Hardware sketch: rough sketch.png (project)",
          size=13, color=THEME["text"], space_before=8, line_spacing=1.35)
    footer(slide, 16, TOTAL)


def build(out: Path):
    prs = new_deck()
    builders = [
        s01_title, s02_architecture, s03_state_control, s04_kinematics,
        s05_wind, s06_estimator, s07_horizon, s08_cost,
        s09_video_storyboard, s10_video_sequence,
        s11_mpc_results, s12_mpc_control, s13_mpc_closing,
        s14_sim_results, s15_sim_scenarios, s16_takeaways,
    ]
    assert len(builders) == TOTAL
    for fn in builders:
        fn(prs)
    out.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(out))
    print(f"Wrote {out}  ({TOTAL} slides)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", type=Path,
                    default=Path(__file__).parent / "Luna_Parafoil_NMPC_Math.pptx")
    args = ap.parse_args()
    required = [
        "diagram_closed_loop.png", "diagram_kinematics.png", "diagram_wind.png",
        "diagram_horizon.png", "diagram_cost.png",
        "mpc_ground_track.png", "mpc_control_wind.png",
        "mpc_range_vs_alt.png", "mpc_trajectory_3d.png",
        "sim_steady_wind_track.png", "mpc_summary.json",
    ]
    missing = [r for r in required if not (ASSETS / r).exists()]
    if missing:
        raise SystemExit(
            "Missing assets — run: python presentation/gen_math_assets.py\n  "
            + "\n  ".join(missing)
        )
    build(args.output)


if __name__ == "__main__":
    main()
